const axios = require('axios');
require('dotenv').config();

const OpenAI = require("openai") ;

const openai = new OpenAI({ apiKey: process.env.GPT_API_KEY});

async function detectStarMethod(question, text) {
    const completion = await openai.chat.completions.create({
        messages: [{ role: "system", content: 'Pretend you are an interviewer. Pretend you gave the candidate the behavioral interview question delimited with double quotation marks. Grade the behavioral interview response delimited with triple quotation marks using the following rubric: \n\n Situation: Explain the situation so that your interviewer understands the context of your example, they do not need to know every detail! \n Task: Talk about the task that you took responsibility for completing or the goal of your efforts. \n Action: describe the actions that you personally took to complete the task or reach the end goal. Highlight skills or character traits addressed in the question. \n Result: Explain the positive outcomes or results generated by your actions or efforts. Here, it is important to highlight quantifiable results. You may also want to emphasize what you learned from the experience or your key takeaways. Your response should be in this quoted format: "Situation: -/10 \nTask: -/5 \nAction: -/20 \nResult: -/5 \n\n' + '""' + question + '""' + '\n\n' + '"""' + text + '"""'}],
        model: "gpt-3.5-turbo",
    });

    return completion.choices[0].message.content;
    // console.log(completion.choices[0].message.content);
}
  

// const inputText = "During my undergraduate studies, I encountered a challenging task that significantly contributed to my personal and professional growth. I was part of a medical outreach program in a rural community where access to healthcare was limited. Our task was to organize a health camp to provide essential medical services to the local population. One of the major challenges we faced was coordinating with various stakeholders, including healthcare professionals, local authorities, and community leaders. Additionally, we had to overcome logistical issues, such as transportation of medical supplies and setting up temporary medical facilities in a resource-constrained environment. To address these challenges, I took the initiative to establish effective communication channels among team members and stakeholders. I organized regular meetings to ensure everyone was on the same page regarding their roles and responsibilities. By collaborating with local leaders, we gained valuable insights into the community's needs and expectations. Logistical challenges were addressed through meticulous planning. I worked closely with a logistics team to create a detailed inventory of medical supplies, arrange transportation, and set up a functional medical camp. This involved adapting to unexpected changes and making quick decisions to ensure the smooth execution of the outreach program. The most rewarding part of this experience was witnessing the positive impact on the community. We provided medical services, health education, and preventive care, significantly improving the well-being of the residents. The challenges I encountered during this task taught me the importance of adaptability, effective communication, and leadership in the field of healthcare. Reflecting on this experience, I have gained a deeper appreciation for the complexities of delivering healthcare in diverse settings. It reinforced my commitment to pursuing a career in medicine, where I can continue to contribute to the well-being of underserved communities and address healthcare disparities.";

// detectStarMethod(inputText)
// .then((result) => {
//     console.log(result)
// })
// .catch((error) => {
//     console.error('Error:', error.message);
// });



module.exports = detectStarMethod;